epoll_named_pipe_virtualconsole: epoll_named_pipe_virtualconsole.c
	gcc -Wall -Werror -o $@ epoll_named_pipe_virtualconsole.c

epoll_named_pipe_virtualoperator: epoll_named_pipe_virtualoperator.c
	gcc -Wall -Werror -o $@ epoll_named_pipe_virtualoperator.c
	 
clean:
	@rm -v epoll_named_pipe_virtualconsole epoll_named_pipe_virtualoperator

all: epoll_named_pipe_virtualconsole epoll_named_pipe_virtualoperator


