epoll_named_pipe_virtualconsole: epoll_named_pipe_virtualconsole.c
	gcc -Wall -Werror -o $@ epoll_named_pipe_virtualconsole.c
 
clean:
	@rm -v epoll_named_pipe_virtualconsole

all: epoll_named_pipe_virtualconsole
